### ISSUE TITLE
Warning and error

### ISSUE THREAD

**Issue by Cbarneron1** [logicexpertise/moodle-mod_onlyoffice#13]
Hi @logicexpertise  ,i have  installed this onlyoffice plugin on my moodle server(v3.11.5)
but we have a warning and a error when we use this plugin.And 0 log for see the error.
My onlyoffice server is a v6.4.
Could you provide a solution to our problem, I attach the capture of the warning and the error.
Thanks  
![error](https://user-images.githubusercontent.com/97873397/149729101-80a6ce71-e3f2-4d1b-b751-f690cb50bdda.png)
![warning](https://user-images.githubusercontent.com/97873397/149729106-c22fb0a8-5860-4131-a2ef-d9a4ccafa716.png)

**Comment by logicexpertise** [comment]
@Cbarneron1 are you using a document server secret in your plugin settings?

If you are not using a secret, the values of _services.CoAuthoring.secret.inbox.string_ and _services.CoAuthoring.secret.outbox.string_ in the Document server should be set to empty strings, and the token.enable.* should be set to false. Refer to Refer to this page - [](https://api.onlyoffice.com/editors/signature/) for instructions on how to set those values.

If you are using a secret, ensure that the above values are set to the same as the document server secret set in the plugin, and the _token.enable.*_ values are set to true.

**Comment by Cbarneron1** [comment]
We made the changes as in the doc, but we still have the same problems.
I am attaching the logs observed on our servers .Could you provide a solution to our problem.
Thanks

[moodle_onlyoffice (1).log](https://github.com/logicexpertise/moodle-mod_onlyoffice/files/7895627/moodle_onlyoffice.1.log)

**Comment by logicexpertise** [comment]
@Cbarneron1 I see a couple of 404 errors in your Apache error logs. Can you check that your Moodle site is not blocking inbound traffic on port 443.

**Comment by logicexpertise** [comment]
@Cbarneron1 Check that your Moodle site is not using a self-signed certificate.

**Comment by Cbarneron1** [comment]
@logicexpertise  we don't use a self signed certificate , and all port at open

**Comment by logicexpertise** [comment]
@Cbarneron1 Confirm that you've downloaded and installed the latest version of the plugin - https://github.com/logicexpertise/moodle-mod_onlyoffice/releases/tag/v3.10.8

Given I have tested this and it works with OnlyOffice 6.4, I don't believe the issue you're having is caused by a bug in the plugin. However let me know if you do find a bug and I'll try to fix it asap.

**Comment by Cbarneron1** [comment]
hey @logicexpertise ,
 We have check and seeing the problem.
The problem comes from our configuration .
 We have correct them , we can close this issue.
Thanks for the help and the support.
