### ISSUE TITLE
Missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [logicexpertise/moodle-mod_onlyoffice#14]
just copying a few other issues in here after reviewing ascensios fork FYI.

Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin stores user data in a number of tables which will need to be included in the privaci api classes.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

Please note - as your plugin interacts with an external system we typcially require the privacy api to be implement prior to plugins db approval.

**Comment by logicexpertise** [comment]
Thanks for reporting this issue @danmarsden 
I'll aim to work on it over the next few days.
