### ISSUE TITLE
Missing backup api

### ISSUE THREAD

**Issue by danmarsden** [logicexpertise/moodle-mod_onlyoffice#15]
It appears that the backup api is missing - please note, that backup/restore support is typically a requirement for approval in the plugins db

**Comment by logicexpertise** [comment]
Thanks for reporting this issue @danmarsden 
I'll aim to work on it over the next few days. In the meantime I've submitted the plugin for approval - https://tracker.moodle.org/browse/CONTRIB-8835

**Comment by logicexpertise** [comment]
Backup API implemented in latest release.
