### ISSUE TITLE
Incorrect use of AJAX_SCRIPT

### ISSUE THREAD

**Issue by mudrd8mz** [logicexpertise/moodle-mod_onlyoffice#17]
https://github.com/logicexpertise/moodle-mod_onlyoffice/blob/bd2eb0ae2235c5ac867eb6e665b90ea6a3081c94/dsconfig.php#L26

This is not how the constant is supposed to be used.

The point is to define it unconditionally _before_ loading the main config.php. So that the environment can be set up appropriately. This affects things like the format of thrown exceptions etc.

**Comment by logicexpertise** [comment]
Resolved
