### ISSUE TITLE
Frozen screen on Moodle4.0

### ISSUE THREAD

**Issue by baltaner** [logicexpertise/moodle-mod_onlyoffice#19]
Hello,
thx for this great plugin, but it doesn't work with Moodle 4.0.
After updateing from Moodle3.11 to 4.0 the onlyoffice window seems to be frozen.
See attached screenshot:

Thanks

![Screenshot 2022-04-25 145909](https://user-images.githubusercontent.com/29839738/165094214-a50e96cb-0b4c-46b9-8f41-a29a5e362bbb.png)
!

**Comment by logicexpertise** [comment]
@baltaner Thanks for reporting the issue.
It has been fixed in the latest release - [v4.0_6.4](https://github.com/logicexpertise/moodle-mod_onlyoffice/releases/tag/v4.0_6.4)
